greenery:

  outputs:
    dbt_zkan:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      user: postgres
      pass: "{{ env_var('DBT_ENV_SECRET_PG_PASSWORD') }}"
      dbname: greenery
      schema: dbt_zkan

    prod:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      user: postgres
      pass: "{{ env_var('DBT_ENV_SECRET_PG_PASSWORD') }}"
      dbname: greenery
      schema: prod

    dbt_non_bigquery:
      type: bigquery
      method: service-account
      project: project-3826e055-85ee-4d4f-a24
      dataset: dbt_non
      threads: 1
      keyfile: /workspaces/data-engineering-bootcamp/00-bootcamp-project/cert/deb-dbt.json
      location: asia-southeast1

    prod_bigquery:
      type: bigquery
      method: service-account
      project: project-3826e055-85ee-4d4f-a24
      dataset: deb_bootcamp
      threads: 1
      keyfile: /workspaces/data-engineering-bootcamp/00-bootcamp-project/cert/YOUR-KEYFILE.json
      location: asia-southeast1

  target: dbt_non_bigquery